repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.6
    hooks:
      # Linter
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args:
        - --line-length=80
        - --ignore=D203,E111,E203,F401
        - src/
        - tests/
      # Formatter
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args:
        - --line-length=80
        - src/
        - tests/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src/", "tests/"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.22.0
    hooks:
      - id: commitizen
