site_name: Documentação Polars-Python

repo_url: https://github.com/Fenyx-Forte/Polars-Python
repo_name: Polars-Python

nav:
  - Repositório:
    - Repositório: index.md

  - Pastas:
    - Pastas: pastas/index.md

    - Arquivos Soltos:
      - Arquivos Soltos: pastas/arquivos_soltos/index.md
      - gitignore: pastas/arquivos_soltos/gitignore.md
      - pre-commit-config: pastas/arquivos_soltos/pre-commit-config.md
      - mkdocs: pastas/arquivos_soltos/mkdocs.md
      - readme: pastas/arquivos_soltos/read_me.md
      - poetry: pastas/arquivos_soltos/poetry.md
      - pyproject: pastas/arquivos_soltos/pyproject.md

    - Configurações:
      - Configurações: pastas/configuracoes/index.md
      - Polars: pastas/configuracoes/polars.md
      - Logging: pastas/configuracoes/logging.md

    - Dados:
      - Dados: pastas/dados/index.md
      - Originais: pastas/dados/originais.md
      - Processados: pastas/dados/processados.md

    - Logs:
      - Logs: pastas/logs/index.md
      - Debug: pastas/logs/debug.md
      - Info: pastas/logs/info.md
      - Error: pastas/logs/error.md

    - Recursos: pastas/recursos.md

    - Relatórios: pastas/relatorios.md

    - SQL: pastas/sql.md

    - SRC: pastas/src.md

    - Testes: pastas/testes.md

  - Python:
    - Python: python/index.md
    - ETL:
      - ETL: python/etl/index.md
      - Lendo Dados: python/etl/reading_data.md
      - Transformando Dados: python/etl/transforming_data.md
      - Salvando Dados: python/etl/loading_data.md
      - Rotina ETL: python/etl/etl_routine.md
      - DataFrame Utils: python/etl/dataframe_utils.md
    - Apresentação:
      - Apresentação: python/apresentacao/index.md
      - Imagens: python/apresentacao/images.md
      - Jinja Template: python/apresentacao/jinja_template.md
      - PDF: python/apresentacao/pdf.md
      - Polars Para HTML: python/apresentacao/polars_to_html.md
    - Utils:
      - Utils: python/utils/index.md
      - DuckDB SQL: python/utils/duckdb_sql.md
      - Log: python/utils/my_log.md
      - Tempo: python/utils/my_time.md

  - Testes:
    - Testes: testes/index.md
    - T1: testes/t1.md
    - T2: testes/t2.md

  - SQL:
    - SQL: sql/index.md

  - Recursos:
    - Recursos: recursos/index.md

  - Relatórios:
    - Relatórios: relatorios/index.md

plugins:
  - mkdocstrings
  - search

theme:
  name: material
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fenyxforte/
      name: LinkedIn Fenyx Forte

    - icon: fontawesome/brands/github
      link: https://github.com/Fenyx-Forte
      name: GitHub Fenyx Forte
