[tool.poetry]
name = "polars-python"
version = "0.1.0"
description = ""
authors = ["Fenyx-Forte <fenyxforte@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
polars = {extras = ["all"], version = "^0.20.19"}
duckdb = "^0.10.1"
ipykernel = "^6.29.4"
fastexcel = "^0.10.4"
pdfkit = "^1.0.0"
jinja2 = "^3.1.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
ruff = "^0.3.7"
bandit = "^1.7.8"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
coverage = "^7.4.4"
pytest-cov = "^5.0.0"
faker = "^24.8.0"

[tool.ruff]
line-length = 80
target-version = "py310"
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py", "src/*.py", "tests/*.py"]

[tool.ruff.lint]
ignore = ["D203", "E111", "E203", "F401"]

[tool.bandit]
skips = ["B101"]

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
